#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Yuto Shibusawa
# SPDX-License-Identifier: BSD-3-Clause

import sys
　                   #2行あけましょう

def tonum(s):
    try:
        return int(s)
    except:
        return float(s)
　                   #2行あけましょう

ans = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)

